services:
  - type: web
    name: construction-material-tracker
    env: python
    buildCommand: pip install -r requirements.txt && python -c "from app import app, db; app.app_context().push(); db.create_all(); print('Database initialized')"
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: construction-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 10

databases:
  - name: construction-db
    databaseName: construction_tracker
    plan: free