services:
  - type: web
    name: construction-material-tracker
    env: python
    buildCommand: pip install -r deploy_requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app_deploy:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: construction-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 10

databases:
  - name: construction-db
    databaseName: construction_tracker
    plan: free