# Render Blueprint - Manual Database Configuration
# Note: Create PostgreSQL database separately and set DATABASE_URL manually
services:
  - type: web
    name: construction-material-tracker
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-eng
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 30
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 10

# Database should be created separately to avoid hostname issues
# Then set DATABASE_URL manually in the web service environment