services:
  - type: web
    name: construction-material-tracker
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-eng
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: construction-tracker-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 10

databases:
  - name: construction-tracker-db
    databaseName: construction_tracker
    plan: free