# Render Blueprint Configuration
# Note: DATABASE_URL should be set manually in Render dashboard
services:
  - type: web
    name: construction-material-tracker
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-eng
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 10

# Database will be configured manually via environment variables
# This avoids the hostname resolution issue